/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.fee_report_system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author singh
 */
public class EditStudent extends javax.swing.JFrame {

    /**
     * Creates new form EditStudent
     */
    public EditStudent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Rollno = new javax.swing.JTextField();
        loadRecordbt = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        Email = new javax.swing.JTextField();
        Course = new javax.swing.JTextField();
        Fee = new javax.swing.JTextField();
        Paid = new javax.swing.JTextField();
        Due = new javax.swing.JTextField();
        Address = new javax.swing.JTextField();
        City = new javax.swing.JTextField();
        State = new javax.swing.JTextField();
        Country = new javax.swing.JTextField();
        Phone = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        updateStudent = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Roll No.");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 32, 84, 34));

        Rollno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RollnoActionPerformed(evt);
            }
        });
        getContentPane().add(Rollno, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 36, 280, -1));

        loadRecordbt.setBackground(new java.awt.Color(204, 255, 255));
        loadRecordbt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        loadRecordbt.setText("Load Record");
        loadRecordbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadRecordbtActionPerformed(evt);
            }
        });
        getContentPane().add(loadRecordbt, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, 169, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(882, 85, 1, -1));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Name :");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 38, 111, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Email :");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 88, 111, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Course :");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 134, 111, 35));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Fee");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 181, 111, 27));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Paid :");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 222, 111, 31));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Due :");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 280, 111, 27));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Address :");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 343, 111, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setText("State : ");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, 111, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setText("City :");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, 111, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setText("Country :");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 482, 111, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setText("Contact No. :");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 529, -1, -1));

        Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameActionPerformed(evt);
            }
        });
        jPanel2.add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 37, 278, -1));
        jPanel2.add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 87, 278, -1));
        jPanel2.add(Course, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 138, 278, -1));
        jPanel2.add(Fee, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 181, 278, -1));
        jPanel2.add(Paid, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 224, 278, -1));
        jPanel2.add(Due, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 280, 278, -1));
        jPanel2.add(Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 327, 278, 44));
        jPanel2.add(City, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 389, 278, -1));
        jPanel2.add(State, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 436, 278, -1));
        jPanel2.add(Country, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 481, 278, -1));

        Phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhoneActionPerformed(evt);
            }
        });
        jPanel2.add(Phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 528, 278, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 51, 51));
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(524, 37, 197, -1));

        updateStudent.setBackground(new java.awt.Color(204, 255, 255));
        updateStudent.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        updateStudent.setText("Update Student");
        updateStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateStudentActionPerformed(evt);
            }
        });
        jPanel2.add(updateStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 580, 240, 60));

        jButton3.setBackground(new java.awt.Color(204, 255, 255));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 590, 120, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 95, 876, 660));

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 100));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RollnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RollnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RollnoActionPerformed

    private void NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameActionPerformed

    private void PhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhoneActionPerformed

    private void loadRecordbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadRecordbtActionPerformed
        // TODO add your handling code here:
        
        getData();
    }//GEN-LAST:event_loadRecordbtActionPerformed

    private void updateStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateStudentActionPerformed
        // TODO add your handling code here:
        updateData();
    }//GEN-LAST:event_updateStudentActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        AccountantSection ob=new AccountantSection();
        ob.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed
    String roll;
    //String name,email,course,fee,paid,due,address,city,state,country,phone;
    
    void getData()
    {
         roll = Rollno.getText();
        try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");     //Loading the driver with driver name, get it from database properties                                     
            String url="jdbc:mysql://localhost:3306/addstudent?zeroDateTimeBehavior=CONVERT_TO_NULL"; 
            Connection con=DriverManager.getConnection(url,"root","$arthak2503");  //Connection Estabhlishing
            String sql="select * from student WHERE RollNo = "+roll;  //Sql Query to get some data
            PreparedStatement st=con.prepareStatement(sql);
            ResultSet rs=st.executeQuery();
            while(rs.next())
            {
                Name.setText(rs.getString(2));
                Email.setText(rs.getString(3));
                Course.setText(rs.getString(4));
                Fee.setText(rs.getString(5));
                Paid.setText(rs.getString(6));
                Due.setText(rs.getString(7));
                Address.setText(rs.getString(8));
                City.setText(rs.getString(9));
                State.setText(rs.getString(10));
                Country.setText(rs.getString(11));
                Phone.setText(rs.getString(12));
            }
            
        }
        catch(Exception e)
        {
            e.getStackTrace();
        }
    }
    
    
    void updateData()
    {
        roll=Rollno.getText();
        try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");     //Loading the driver with driver name, get it from database properties                                     
            String url="jdbc:mysql://localhost:3306/addstudent?zeroDateTimeBehavior=CONVERT_TO_NULL"; 
            Connection con=DriverManager.getConnection(url,"root","$arthak2503");  //Connection Estabhlishing
           String sql="update student set Name=?, Email=?, Course=?, Fee=?, Paid=?, Due=?, Address=?, City=?, State=?, Country=?, ContactNo=? where RollNo=? ";  //Sql Query to get some data
            PreparedStatement st=con.prepareStatement(sql);
            st.setString(1,Name.getText());
            st.setString(2,Email.getText());
            st.setString(3,Course.getText());
            st.setString(4,Fee.getText());
            st.setString(5,Paid.getText());
            st.setString(6,Due.getText());
            st.setString(7,Address.getText());
            st.setString(8,City.getText());
            st.setString(9,State.getText());
            st.setString(10,Country.getText());
            st.setString(11,Phone.getText());
            st.setString(12,roll);
            
            int i=st.executeUpdate();
            
            if(i>0){
                JOptionPane.showMessageDialog(this,"Student Update Successfully"); //A window Pane pops 
            }
            else{
                JOptionPane.showMessageDialog(this,"Student Not Updated");
            }
              
                      
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Address;
    private javax.swing.JTextField City;
    private javax.swing.JTextField Country;
    private javax.swing.JTextField Course;
    private javax.swing.JTextField Due;
    private javax.swing.JTextField Email;
    private javax.swing.JTextField Fee;
    private javax.swing.JTextField Name;
    private javax.swing.JTextField Paid;
    private javax.swing.JTextField Phone;
    private javax.swing.JTextField Rollno;
    private javax.swing.JTextField State;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton loadRecordbt;
    private javax.swing.JButton updateStudent;
    // End of variables declaration//GEN-END:variables
}
